// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // In Prisma 7, the connection URL lives here in config, NOT in schema.prisma
    url: process.env["DATABASE_URL"] ?? "",
  },
});
