import { File, Paths } from "expo-file-system";
import { ImageManipulator, SaveFormat } from "expo-image-manipulator";
import * as ImagePicker from "expo-image-picker";
import { chooseProfilePhoto, type CropRect, type Photo } from "./profile-photo";

export function pickProfilePhoto() {
  return chooseProfilePhoto({
    permission: () => ImagePicker.requestMediaLibraryPermissionsAsync(),
    launch: () => ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: false, allowsMultipleSelection: false, quality: 1 }),
    async prepare(photo) {
      // Render once to normalize orientation and keep the interactive preview small.
      const context = ImageManipulator.manipulate(photo.uri);
      try {
        if (Math.max(photo.width, photo.height) > 1600)
          context.resize(photo.width >= photo.height ? { width: 1600 } : { height: 1600 });
        const image = await context.renderAsync();
        try { return await image.saveAsync({ format: SaveFormat.JPEG, compress: 0.95 }); }
        finally { image.release(); }
      } finally { context.release(); }
    },
  });
}
export async function renderProfileCrop(photo: Photo, rect: CropRect) {
  const context = ImageManipulator.manipulate(photo.uri);
  try {
    context.crop(rect).resize({ width: 512, height: 512 });
    const image = await context.renderAsync();
    try { return await image.saveAsync({ format: SaveFormat.JPEG, compress: 0.9 }); }
    finally { image.release(); }
  } finally { context.release(); }
}
export const profilePhotoFiles = {
  async copy(uri: string) {
    const destination = new File(Paths.document, `leafcheck-profile-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}.jpg`);
    try { new File(uri).copy(destination); }
    catch (error) { if (destination.exists) destination.delete(); throw error; }
    return destination.uri;
  },
  remove(uri: string) {
    const file = new File(uri);
    // Only delete files generated by this feature inside this app's documents directory.
    if (file.parentDirectory.uri === Paths.document.uri && /^leafcheck-profile-[a-z0-9-]+\.jpg$/.test(file.name) && file.exists)
      file.delete();
  },
};
