import assert from "node:assert/strict";
import test from "node:test";
import { ApiError, createApiClient } from "../services/api";
import type { SessionState } from "../services/session";
const plantId = "11111111-1111-4111-8111-111111111111";
const deviceId = "22222222-2222-4222-8222-222222222222";
const timestamp = "2026-10-05T00:00:00.000Z";
const device = { id: deviceId, userId: plantId, name: "Sensor", macAddress: "LC-A50528", status: "OFFLINE", createdAt: timestamp, updatedAt: timestamp };
const plant = { id: plantId, deviceId, name: "Fern", species: "Fern", healthStatus: "healthy", createdAt: timestamp, updatedAt: timestamp };
const telemetry = { deviceId: device.macAddress, timestamp, environment: { temperatureCelsius: 0, humidityPercentage: 0 }, soilMoisture: { percentage: 0, rawAnalogValue: 0, status: "dry" }, lightLevel: { lux: 0, status: "insufficient" } };
const validation = (error: unknown) => error instanceof ApiError && error.kind === "validation";
test("empty successful responses reject when contracts require a payload", async () => {
  const api = createApiClient({ fetch: async () => new Response(null, { status: 204 }) });
  await assert.rejects(api.claimDevice(device.macAddress), validation);
  await assert.rejects(api.pairDeviceToPlant(plantId, deviceId), validation);
  await assert.rejects(api.fetchPlantTelemetry(plantId), validation);
  assert.equal(await api.deletePlant(plantId), undefined);
});
test("device routes preserve UUID/MAC, bodies, bearer and all BFF states", async () => {
  const responses: unknown[] = [device, plant, { ...plant, deviceId: undefined }, { paired: false, device: null, telemetry: null }, { paired: true, device, telemetry: null }, { paired: true, device, telemetry }];
  const calls: { url: string; init?: RequestInit }[] = [];
  const api = createApiClient({ baseUrl: "http://test", fetch: async (url, init) => { calls.push({ url: String(url), init }); return Response.json(responses.shift()); } });
  assert.equal((await api.claimDevice(" lc-a50528 ", " Sensor ", { accessToken: "access" })).id, deviceId);
  await api.pairDeviceToPlant(plantId, deviceId);
  await api.pairDeviceToPlant(plantId, null);
  assert.equal((await api.fetchPlantTelemetry(plantId)).paired, false);
  assert.equal((await api.fetchPlantTelemetry(plantId)).telemetry, null);
  assert.deepEqual((await api.fetchPlantTelemetry(plantId)).telemetry, telemetry);
  assert.equal(calls[0].url, "http://test/api/devices/claim");
  assert.equal(calls[0].init?.method, "POST");
  assert.equal(new Headers(calls[0].init?.headers).get("Authorization"), "Bearer access");
  assert.deepEqual(JSON.parse(String(calls[0].init?.body)), { macAddress: device.macAddress, name: "Sensor" });
  assert.equal(calls[1].url, `http://test/api/plants/${plantId}/pair-device`);
  assert.equal(calls[1].init?.method, "PATCH");
  assert.deepEqual(JSON.parse(String(calls[1].init?.body)), { deviceId });
  assert.deepEqual(JSON.parse(String(calls[2].init?.body)), { deviceId: null });
  assert.equal(calls[3].url, `http://test/api/plants/${plantId}/telemetry`);
  assert.equal(calls[3].init?.method, "GET");
});
test("invalid inputs reject before transport and conventional MACs normalize", async () => {
  let calls = 0;
  const api = createApiClient({ fetch: async () => { calls++; return Response.json(device); } });
  for (const mac of ["", "not-a-mac", deviceId]) assert.throws(() => api.claimDevice(mac), validation);
  for (const name of [" ", "x".repeat(101)]) assert.throws(() => api.claimDevice(device.macAddress, name), validation);
  assert.throws(() => api.pairDeviceToPlant("mock", deviceId), validation);
  assert.throws(() => api.pairDeviceToPlant(plantId, device.macAddress), validation);
  assert.throws(() => api.fetchPlantTelemetry("mock"), validation);
  assert.equal(calls, 0);
  for (const mac of ["aa:bb:cc:dd:ee:ff", "aa-bb-cc-dd-ee-ff"]) await api.claimDevice(mac);
  assert.equal(calls, 2);
});
test("conflicts and malformed successful responses never become success", async () => {
  const api = (body: unknown, status = 200) => createApiClient({ fetch: async () => Response.json(body, { status }) });
  await assert.rejects(api({ error: "Already claimed" }, 409).claimDevice(device.macAddress), (e: unknown) => e instanceof ApiError && e.status === 409);
  for (const body of [{}, { ...device, id: device.macAddress }, { ...device, status: "fake" }]) await assert.rejects(api(body).claimDevice(device.macAddress), validation);
  for (const body of [{ paired: false, device, telemetry: null }, { paired: true, device: null, telemetry: null }, { paired: true, device }, { paired: true, device, telemetry: { ...telemetry, deviceId } }, { paired: true, device, telemetry: { ...telemetry, environment: null } }]) await assert.rejects(api(body).fetchPlantTelemetry(plantId), validation);
  await assert.rejects(api({ ...plant, id: "mock" }).pairDeviceToPlant(plantId, deviceId), validation);
});
test("new routes refresh once and respect cancellation and timeout", async () => {
  let state: SessionState = { status: "authenticated", user: null, token: "old", generation: 1, error: null };
  const boundary = new AbortController();
  const tokens: (string | null)[] = [];
  let refreshes = 0;
  const api = createApiClient({ fetch: async (_url, init) => { tokens.push(new Headers(init?.headers).get("Authorization")); return tokens.length === 1 ? Response.json({}, { status: 401 }) : Response.json(device); } });
  api.bindSession({ snapshot: () => state, signal: () => boundary.signal, refresh: async () => { refreshes++; state = { ...state, token: "new" }; }, reject: () => assert.fail("unexpected rejection") });
  await api.claimDevice(device.macAddress);
  assert.equal(refreshes, 1);
  assert.deepEqual(tokens, ["Bearer old", "Bearer new"]);
  const hanging = createApiClient({ fetch: () => new Promise(() => {}), timeoutMs: 10 });
  await assert.rejects(hanging.fetchPlantTelemetry(plantId), (e: unknown) => e instanceof ApiError && e.kind === "timeout");
  hanging.bindSession({ snapshot: () => state, signal: () => boundary.signal, refresh: async () => {}, reject: () => {} });
  const pending = hanging.pairDeviceToPlant(plantId, deviceId, { timeoutMs: 1000 });
  state = { ...state, generation: 2 };
  boundary.abort();
  await assert.rejects(pending, (e: unknown) => e instanceof ApiError && e.kind === "cancelled");
  const abort = new AbortController();
  abort.abort();
  await assert.rejects(api.claimDevice(device.macAddress, undefined, { signal: abort.signal }), (e: unknown) => e instanceof ApiError && e.kind === "cancelled");
});
